@startuml overview
left to right direction
skinparam defaultTextAlignment center

rectangle "<b>Applications</b>" as Apps
rectangle "<b>Humans</b>" as Humans

rectangle "<b>Port 4317</b>\nOTLP gRPC" as Port4317
rectangle "<b>Port 4318</b>\nOTLP HTTP" as Port4318
rectangle "<b>Port 3000</b>\nGrafana" as Port3000

rectangle "jmerle/opentelemetry-stack" {
    rectangle "<b>OpenTelemetry Collector</b>\nIngester" as OTelCol
    rectangle "<b>VictoriaMetrics</b>\nMetrics Database" as VictoriaMetrics
    rectangle "<b>Loki</b>\nLogs Database" as Loki
    rectangle "<b>Tempo</b>\nTraces Database" as Tempo
    rectangle "<b>Grafana</b>\nVisualization" as Grafana
}

Apps --> Port4317
Apps --> Port4318

Port4317 --> OTelCol
Port4318 --> OTelCol

OTelCol --> VictoriaMetrics
OTelCol --> Tempo
OTelCol --> Loki

VictoriaMetrics <-- Grafana
Tempo <-- Grafana
Loki <-- Grafana

Grafana <-- Port3000
Port3000 <-- Humans
@enduml
