{
 "title": "OpenTelemetry Stack Overview",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vm_app_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active time series",
   "type": "stat",
   "description": "Number of <a href=\"https://docs.victoriametrics.com/faq/#what-is-an-active-time-series\">active time series</a> (time series that received a sample or were queried within the last hour)",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vm_cache_entries{type=\"storage/hour_metric_ids\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total datapoints",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_rows{type!~\"indexdb.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total traces",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tempodb_backend_objects_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VictoriaMetrics version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vm_app_version", "legendFormat": "{{short_version}}" }
   ]
  },
  {
   "title": "Tempo version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tempo_build_info", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Loki version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "loki_build_info", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Pyroscope version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pyroscope_build_info", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "100% = 1 core",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(opentelemetrystack_cpu_usage_seconds_total[$__rate_interval])",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "opentelemetrystack_physical_memory_usage_bytes",
     "legendFormat": "Physical memory"
    },
    {
     "expr": "opentelemetrystack_swap_memory_usage_bytes > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(opentelemetrystack_disk_usage_bytes)",
     "legendFormat": "Disk usage"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(opentelemetrystack_disk_usage_bytes, \"component\", \"$1\", \"path\", \"/data/(.*)\")",
     "legendFormat": "{{component}}"
    }
   ]
  },
  { "title": "VictoriaMetrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Total datapoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum(vm_rows{type!~\"indexdb.*\"})",
     "legendFormat": "Datapoints"
    }
   ]
  },
  {
   "title": "Active time series",
   "type": "timeseries",
   "description": "Number of <a href=\"https://docs.victoriametrics.com/faq/#what-is-an-active-time-series\">active time series</a> (time series that received a sample or were queried within the last hour)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "vm_cache_entries{type=\"storage/hour_metric_ids\"}",
     "legendFormat": "Active time series"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "opentelemetrystack_disk_usage_bytes{path=\"/data/victoria-metrics\"}",
     "legendFormat": "Disk usage"
    }
   ]
  },
  {
   "title": "Ingestion rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rate(vm_rows_inserted_total[$__rate_interval]) > 0",
     "legendFormat": "{{type}} (datapoints per second)"
    }
   ]
  },
  {
   "title": "Mean disk usage per datapoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "opentelemetrystack_disk_usage_bytes{path=\"/data/victoria-metrics\"} / sum(vm_rows{type!~\"indexdb.*\"})",
     "legendFormat": "Disk usage"
    }
   ]
  },
  {
   "title": "Mean disk usage per time series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "opentelemetrystack_disk_usage_bytes{path=\"/data/victoria-metrics\"} / count({__name__=~\".*\"})",
     "legendFormat": "Disk usage"
    }
   ]
  },
  { "title": "Tempo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Total traces",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(tempodb_backend_objects_total)",
     "legendFormat": "Traces"
    }
   ]
  },
  {
   "title": "Ingestion rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rate(tempo_ingester_traces_created_total[$__rate_interval])",
     "legendFormat": "Traces per second"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "opentelemetrystack_disk_usage_bytes{path=\"/data/tempo\"}",
     "legendFormat": "Disk usage"
    }
   ]
  },
  {
   "title": "Mean disk usage per trace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "opentelemetrystack_disk_usage_bytes{path=\"/data/tempo\"} / sum(tempodb_backend_objects_total)",
     "legendFormat": "Disk usage"
    }
   ]
  },
  { "title": "Loki", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "opentelemetrystack_disk_usage_bytes{path=\"/data/loki\"}",
     "legendFormat": "Disk usage"
    }
   ]
  },
  {
   "title": "Ingestion rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rate(loki_bytes_per_line_count[$__rate_interval])",
     "legendFormat": "Log lines per second"
    }
   ]
  },
  { "title": "Pyroscope", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "opentelemetrystack_disk_usage_bytes{path=\"/data/pyroscope\"}",
     "legendFormat": "Disk usage"
    }
   ]
  }
 ]
}