server:
  http_listen_port: 4040
  grpc_listen_port: 9097

distributor:
  ring:
    kvstore:
      store: inmemory

limits:
  compactor_blocks_retention_period: 336h

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory

store_gateway:
  bucket_store:
    sync_dir: /data/pyroscope/sync

pyroscopedb:
  data_path: /data/pyroscope

compactor:
  data_dir: /data/pyroscope/compactor

storage:
  backend: filesystem
  filesystem:
    dir: /data/pyroscope/shared
